### ISSUE TITLE
Question - Just slugs or content of page too?

### ISSUE THREAD

**Issue by i001962** [joshuap/gatsby-starter-roam#1]
@joshuap nicely done. I've tried pulling in the https://roamresearch.com/#/app/help database and get all the slugs and pages created but no content on the pages. Before diving into the json structure and gatsby-node.js I thought I'd ask if you've done that yet.

**Comment by joshuap** [comment]
Hey! I have a branch where I’d started on content creation, but it’s not completely worked out. I’ll push it up later this afternoon if you want to take a look (I forget exactly where I’d left it).

**Comment by i001962** [comment]
In the meantime I ran across this repo which you may find interesting https://github.com/mathieudutour/gatsby-digital-garden 

One thing I did notice is roam has a field called children as does Gatsby. I need to change that field name in roam.json to gain access to it via graphql. 

All the best

**Comment by joshuap** [comment]
@i001962 oh I had not seen that--that collection of plugins looks similar to what I had imagined eventually extracting from this starter. I pushed my branch for displaying blocks on pages in the meantime, in case you want to look at that. I ended up just merging it: https://github.com/joshuap/gatsby-starter-roam/commit/e843d4e652aa3b271e42f5439d43b16d51039799
